### ISSUE TITLE
AWS Machine Learning - Linear regression -  Predict Sales for each Product

### ISSUE THREAD

**Issue by ClementRajesh** [jamesandersen/aws-machine-learning-demo#2]
I am newbie in amazon Machine Learning. I could able to generate prediction using Machine learning using "linear regression", however i could not able to find suitable example "For this product, how many units will sell?". My expectation would be to find how many products required in each category in future using prediction. I was expecting simply X & Y axis can be defined in input however amazon Machine learning is expecting only targets and the graph automatically generated. X axis always takes number of records from the input CSV instead count of the product sold.

I need guidance how to proceed further or document or materials to refer further.

Thanks, Raj

**Comment by jamesandersen** [comment]
Hi Raj,
    If you're trying to predict how many units will sell then, when creating your datasource, be sure to select the column that represents how many units *have sold*.   AWS Machine Learning will not automatically select a column for you based on naming conventions.   I've just added a screenshot to the [Creating a Datasource](https://github.com/jamesandersen/aws-machine-learning-demo/blob/master/Create-Datasource.md) page that shows the selection.  I hope it helps.
- James
